### ISSUE TITLE
SERVER_API.md incorrect endpoint (documentation)

### ISSUE THREAD

**Issue by TheRealVish** [anarchy-ai/LLM-VM#170] opened 2023-08-28 17:53 UTC
change https://localhost:3002/v1/completion to endpoint https://localhost:3002/v1/complete and add some examples

**Comment by mmirman** [comment] 2023-08-28 18:58
Related to #144

**Comment by INF800** [comment] 2023-08-28 18:59
it is duplicate of #146

**Comment by VictorOdede** [comment] 2023-10-27 14:40
Fixed by #175

**Closed by VictorOdede** 2023-10-27 14:40 UTC
Labels: bug, SPECIAL ACK
